### ISSUE TITLE
Petab Yaml: Include petabId / modelId

### ISSUE THREAD

**Issue by dlill** [PEtab-dev/PEtab#532]
**Which problem would you like to address? Please describe.**
Reference the name of a petab estimation problem in its yaml file with a `petabId` or `modelId` field.
Until now, the name of a petab is coded implicitly by the naming convention `experimentalCondition_petabId.tsv`, etc. 
In petab_select and potentially other applications we encounter a lot of different models, which might be derived from the same base petab. 
Therefore, having the `petabId` in the yaml would provide more flexibility in terms of renaming the tsv files (not necessary anymore) but still keeping the benefit of having a unique Id for each estimation problem

**Describe the solution you would like**
Inlcude a field `petabId` in the yaml which accepts character inputs

**Describe alternatives you have considered**

**Additional context**
We discussed this in the context of a petab_select meeting. I'm just putting it here so it's not forgotten

**Comment by dweindl** [comment]
Hi @dlill , thanks for your suggestion. We are currently preparing a proposal for allowing non-SBML models in PEtab, this will also include model IDs. More details in about 2 weeks.

**Comment by dweindl** [comment]
@dlill : Sorry for the delay. Would the changes proposed in https://github.com/PEtab-dev/PEtab/pull/538 address your needs?

**Comment by dlill** [comment]
Hey, I am currently moving out of the sysbio-field and will probably not work with petab anymore. But to quickly answer your question, with `modelId` I actually meant `petabId`, to enable referencing the petab problem itself by an ID. This would be helpful e.g. in model selection or also in visual comparisons of different models

```
petabId: myfancypetabId
format_version: 2.0.0
parameter_file: parameters.tsv
problems:
- condition_files:
  - conditions.tsv
  measurement_files:
  - measurements.tsv
  observable_files:
  - observables.tsv
  mapping_file: mappings.tsv # optional 
  models:
    id_for_model1:
      location: model1.xml
      language: sbml
```
